### PR TITLE
hability to check all slaves

### PR DESCRIPTION
**Pull request by theflyingbear**
Hi,
I added the possibility to specify the value "all" for "--connection".
This allow to report the status of all slaves of master.

### CODE REVIEW

**Comment by evasilchenko** [comment]
@theflyingbear seems like the unit tests are currently failing on your branch

**Comment by theflyingbear** [comment]
I guess I should have looked at what is tests.py :(

**Comment by juannyG** [comment]
I'll make sure to add a `CONTRIBUTING.md` to the repos this week, with an explanation on how to run tests. Sorry about that!

FYI - I also have plans to include tox as the test runner to start supporting multiple versions of python as well. Thanks for the interest @theflyingbear !!

**Comment by juannyG** [comment]
Sorry for the delay @theflyingbear - I can see the potential desire for people wanting to summarize all MariaDB slave connections of a DB server into one nagios check which uses all the same warning/critical limits for lag.

I'm going to think about this a bit more on how I would approach this, but by all means, feel free to take another crack at adding this feature. For the time being however, I'll open an issue, reference this PR, but also close it. Thanks again for you interest and I hope it's been helpful!

**Pull request closed without merging**
