### PR TITLE
Performance data for slave-lag

### PR DESCRIPTION
**Pull request by barrypitman**
Please see issue #10

### CODE REVIEW

**Comment by juannyG** [comment]
Thanks for your feedback and this PR.

Looks like we've got a test failure checking the output of the plugin. When you get a chance, if you can resolve that test case, we can go ahead and get your change merged in.

**Comment by barrypitman** [comment]
Sorry about that! I've updated the test, and the test itself seems to be passing, but Travis is failing with this message:
`ERROR: Failed to generate report: No data to report.`
I haven't dealt with python or travis before, so not really sure how to proceed.

**Comment by juannyG** [comment]
Strange - that's a new one. I'll look into it.

**Comment by juannyG** [comment]
Hi @barrypitman - please merge down the changes I just pushed up to the master branch. The package ```pytest-cov``` that I use to generate coverage reports after tests run seems to have changed how a particular parameter needs to be defined in newer versions. Sorry about that.

**Review by marcosmoyano — APPROVED** [review]
legit

**Comment by flickerfly** [comment]
Any idea what those test failures are? I'd like to see this get committed (cause I just replicated the commit before finding this). I'd be glad to pitch in a bit.

**Pull request merged**
